marathon:
  image: llparse/marathon:0.11.0-centos-7
  environment:
    MARATHON_HOSTNAME: 1.2.3.4
    MARATHON_HTTPS_ADDRESS: 1.2.3.4
    MARATHON_HTTP_ADDRESS: 1.2.3.4
    MARATHON_MASTER: zk://node-1:2181,node-2:2181,node-3:2181/mesos
    MARATHON_ZK: zk://node-1:2181,node-2:2181,node-3:2181/marathon
