.catalog:
  version: v1.12.3-2
  minimum_rancher_version: 1.2.0-pre4-rc1
  questions:
  - variable: MANAGER_SCALE
    label: Number of Managers
    description: Desired number of managers to participating in service orchestration. This dictates host resilience.
    required: true
    default: 3
    type: enum
    options:
    - 1
    - 3
    - 5
    - 7
    - 9
swarmkit-mon:
